[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["apps/*", "packages/*"]

[tool.uv.sources]
chatwoot_api = { workspace = true }

[tool.pyright]
typeCheckingMode = "strict"
