[project]
name = "chatwoot-api"
version = "0.0.5"
description = "Example shared package"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.6",
    "pydantic-settings>=2.7.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatchling.build.targets.wheel]
packages = ["src/chatwoot_api"]

[dependency-groups]
dev = ["ruff>=0.9.4"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["E501"]
